### ISSUE TITLE
typeorm 0.3 example

### ISSUE THREAD

**Issue by DawidWetzler** [jepiqueau/vue-sqlite-app-starter#3]
Hello, I've thought that it would be nice to have an example for making it work with latest typeorm version.

This way I have forked your repository and updated it to latest typeorm (0.3.5 atm) version.

https://github.com/DawidWetzler/vue-sqlite-app-starter

**Comment by jepiqueau** [comment]
@DawidWetzler thanks for your work that will help me and others. Can you make a PR i will merge it i saw that your fork is 40 behind.can you update to @capacitor/core /ios /android 3.4.2 and capacitor-community/sqlite@3.4.2 and also the latest of jeep-sqlite.
